# --------------------
# Core spring settings
# --------------------

spring:
  application:
    name: ${rootArtifactId}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  # --------------------
  # Security settings
  # --------------------

  security:
    oauth2:
      resourceserver:
        jwt:
          disabled: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_DISABLED}
          excluded-urls: /swagger-ui/**, /swagger-resources/**, /v3/api-docs/**, /billing-system-errors, /actuator/**, /info
          jws-algorithm: RS256
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

# ---------------
# Server settings
# ---------------

server:
  port: 8080

# ----------------
# Logging settings
# ----------------

logging:
  type: ${LOGGING_TYPE}
  config: ${LOGGING_CONFIG}
  exclude-path: ${LOGGING_EXCLUDE_PATH}
  masquerading:
    max-len: ${LOGGING_MASQUERADING_MAX_LEN}
    invert-default: ${LOGGING_MASQUERADING_INVERT_DEFAULT}
    field-config:
      internal:
        response-body: >
          [
              { "value": "meta", "config": { "min-len": 6, "right": 2, "left": 2 } },
              { "value": "status", "config": { "min-len": 6, "right": 2, "left": 2 } },
              { "value": "code", "config": { "min-len": 6, "right": 2, "left": 2 } },
              { "value": "message", "config": { "min-len": 6, "right": 2, "left": 2 } },
              { "value": "traceparent", "config": { "min-len": 6, "right": 2, "left": 2 } }
          ]
      external:
        feign:
          response-body: >
            [
                { "value": "meta", "config": { "min-len": 6, "right": 2, "left": 2 } },
                { "value": "status", "config": { "min-len": 6, "right": 2, "left": 2 } },
                { "value": "code", "config": { "min-len": 6, "right": 2, "left": 2 } },
                { "value": "message", "config": { "min-len": 6, "right": 2, "left": 2 } },
                { "value": "traceparent", "config": { "min-len": 6, "right": 2, "left": 2 } }
            ]

# --------------------
# Spring doc settings
# --------------------

springdoc:
  api-docs:
    resolve-schema-properties: true

# --------------------
# Spring management settings
# --------------------

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

# --------------------
# Billing system settings
# --------------------

standardized-response:
  enable: true
system:
  cmdb:
    name: RU.BILLING.SYSTEM

# --------------------
# BUSINESS settings
# --------------------
